### ISSUE TITLE
selectCollection don't return error

### ISSUE THREAD

**Issue by lATAl** [uniqueway/redux-crud-store#18]
If an error occurs after fetch collections, selectCollection don't return error object.

**Comment by devvmh** [comment]
Hi thanks for posting an issue!

Could you send me some sample code and data to help me replicate the issue?
In particular, what error did your api return (an http status code?), what
is the (incorrect) output of selectCollection, and what is the output you
were expecting to get from selectCollection?

That'll help me fix the issue. Thanks!

**Comment by devvmh** [comment]
I've reviewed the code and I think I see what you mean - if there is a FETCH_ERROR, selectCollection doesn't give you any indication of that. This is why it's great to have more people using this! We just haven't run into a collection fetch error yet so we never noticed.

I'll make a pull request and send you a message - would you be interested in reviewing the code and testing it?

**Comment by devvmh** [comment]
OK 4.2.1 is published with this change! Thanks!

**Comment by lATAl** [comment]
👍
