### ISSUE TITLE
Function to erase data of model

### ISSUE THREAD

**Issue by lATAl** [uniqueway/redux-crud-store#24]
Hi, I need a function to erase all data of the model. Do you have any idea?

**Comment by devvmh** [comment]
Hi, this sounds like a good idea. I can probably implement this on Monday or Tuesday

Just to make sure I know what you want, you're hoping for a new action and reducer branch that would do something like this, right?

```
// original state:
{
  'posts': {
    byId: {
      1: { ... },
      2: { ... }
    },
    collections: [{
      params: { ... },
      otherInfo: { ... },
      ...
    }],
    actionStatus: {
      create: { ... },
      update: { ... },
      delete: { ... }
    }
  }
}

// run this action:
{
  type: CLEAR_MODEL_DATA,
  payload: { model: 'posts' }
}

// and the state becomes:
{
  posts: {
    byId: {},
    collections: []
    actionStatus: {
      create: {},
      update: {},
      delete: {}
    }
  }
}
```

There are a few other available options. Let's call the one above option (a). Option (b) would be to totally delete the 'posts' key from state.models. Option (c) would go the other direction, and only clear byId, leaving collections and actionStatus the same.

What option do you prefer for your use case? I can't see compelling reasons to go for any of them off the top of my head, other than option (b) would be the simplest to implement. 

Let me know which you prefer and I'll add it and push a new version of the library next week.

**Comment by lATAl** [comment]
I like option (a) 👍

**Comment by devvmh** [comment]
I updated option (a)'s description above to match the initialState variables in reducers.js (create/update/delete get the initial value of `{}` instead of `null`). @lATAl would you be willing to look over this PR and let me know if you spot any problems?

#25
