### ISSUE TITLE
opts argument in select() is not passed to selectCollection()

### ISSUE THREAD

**Issue by alexhung** [uniqueway/redux-crud-store#53]
The `opts` object in `select()` https://github.com/devvmh/redux-crud-store/blob/master/src/selectors.js#L43 is currently not being passed to `selectCollection()` https://github.com/devvmh/redux-crud-store/blob/master/src/selectors.js#L51.

This means `select(..., { interval: 1000 })` has no effect for selecting collection.

**Comment by devvmh** [comment]
Thanks for the detailed report!

I've pushed 0552ed0d58f601a470301e2f8fa3134c47a0a4cf which should fix this. I'm publishing 5.3.0 now. Please try this release and let me know if it works

**Comment by devvmh** [comment]
I'll close this assuming 5.3.0 worked for you. If you still have issues please re-open this 😃
