### ISSUE TITLE
How to keep the new params in render() method on fetch page collection

### ISSUE THREAD

**Issue by shengnian** [uniqueway/redux-crud-store#57]
Nice project, but have a question, here is the code:
```
import React from 'react'
import { connect } from 'react-redux'

import { fetchPosts } from '../../redux/modules/posts'
import { select } from 'redux-crud-store'

class List extends React.Component {
  componentWillMount() {
    const { posts, dispatch } = this.props
    if (posts.needsFetch) {
      dispatch(posts.fetch)
    }
  }

  componentWillReceiveProps(nextProps) {
    const { posts } = nextProps
    const { dispatch } = this.props
    if (posts.needsFetch) {
      dispatch(posts.fetch)
    }
  }

  onHandlePage = (page) => {
    let action = select(fetchPosts({ page: page  }), models)
    if (action.needsFetch) {
      this.props.dispatch(action.fetch)
    }
  }
  
  render() {
    const { posts } = this.props
    if (posts.isLoading) {
      return <div>
        <p>loading...</p>
      </div>
    } else 
    {
      return <div>
        {posts.data.map(post => <li key={post.id}>{post.title}</li>)}
        <p>
        <button onClick={this.onHandlePage(2)}>2</button>
        <button onClick={this.onHandlePage(3)}>3</button>
        </p>
      </div>
    }
  }
}

function mapStateToProps(state, ownProps) {
  return { posts: select(fetchPosts({ page: 1 }), state.models) }
}

export default connect(mapStateToProps)(List)

```
 
when click the button 2 and 3 page step by step. the page index only value 1.
Do i use the error? and How to keep the new params in render() method on fetch page collection?
thanks.

Note: i tried update `mapStateToProps` method to like this:

```
function mapStateToProps(state, ownProps) {
  const params = state.getIn(['models', 'posts', 'collections'], fromJS([{params: { page: 1 }}])).last().get('params').toJS() // when the render execution get the new params

  return { posts: select(fetchPosts(params), state.models) }
}
```

 but the way can do next page is fine. 
 global state look like this:

```
{
  models: {
    posts: {
      collections: [
        {
          params: ... // page 1
          ....
        },
        {
          params: ...// page 2
        },
        {
          params: ...// page 3
        }
      ],
      byId: {
          ...// here some record
      }
    }
  }
}
```
but when click pre page can't work. i don't no why, can help me? thanks

**Comment by devvmh** [comment]
You're definitely on the right track! Just a small tweak to your component is all you need. Are you doing something like infinite scroll?

All the selectors defined by redux-crud-store are really just helper functions. When you call `select(fetchPosts({ page: 1 }), state.models)`, it just delegates to [selectCollection](https://github.com/devvmh/redux-crud-store/blob/master/docs/API.md#selectcollectionmodelname-string-crud-map-params-object-opts-object). You can see the source for selectCollection at https://github.com/devvmh/redux-crud-store/blob/master/src/selectors.js#L67.

If you wanted to, for example, load the current page AND load all the previous pages, you could change mapStateToProps to something like this:

```
function mapStateToProps(state, ownProps) {
  const currentPage = ownProps.currentPage || 1
  return { 
    posts: select(fetchPosts({ page: currentPage }), state.models),
    allPosts: fromJS(state.getIn(['models', 'posts', 'collections']))
  }
}
```

I'm not exactly sure how you'd change your component to use these new values, but it sounds like you have a plan for that.

Does that make sense? Does that help?

**Comment by shengnian** [comment]
thank you for your reply,  I am confused that how to set and change `ownProps.currentPage` value, i'm  used `state.currenPage`  do that, but can't pass the value to mapStateToProps, so i want got the page params from global state, but didn't work.

i tried change the source code `reducer.js` file  'collectionsReducer'  method

```
switch (action.type) {
    case FETCH:
    case FETCH_SUCCESS:
    case FETCH_ERROR:
      // create the collection for the given params if needed
      // entry will be undefined or [index, existingCollection]
      if (action.meta.params === undefined) {
        return state
      }

     // ->>>>here is change and the params can get in compoent's `render()` method
      return state.set(0, collectionReducer(undefined, action))

     
    case CREATE_SUCCESS:
    ...

```

Some of other question:

```
export function select<T>(action: CrudAction<T>, crud: State, opts: SelectorOpts = {}
                         ): Selection<T> {
  const model = action.meta.model
  const params = action.payload.params
  let id
  let selection
  switch (action.type) {
    case FETCH:
      selection = selectCollection(model, crud, params)  // ->> here was not pass to `opts` var, can't config the interval time  
      break
....
```

and `recent` method
`const interval = opts.interval || 10 * 60 * 1000 // ten minutes` to `const interval = (opts && opts.interval) || 10 * 60 * 1000 // ten minutes`

i'm not sure there are question.

**Comment by devvmh** [comment]
I'd encourage you to read the source code, but I would avoid changing it if you can. If you find it's not working, feel free to submit a pull request. Trying to change an npm package's code usually just confuses me more than helps!

You would need to modify your component to be able to add `currentPage` to your props. I'm not sure what the best way to do this is. 

One option is to dispatch actions to the store that update a current page key in the store. 

Another option is to create a wrapper component that looks like:

```
class ListWrapper extends React.Component {
  constructor(props) {
    this.state = { page: 1 }
  }
  render() {
    return <List 
      changeCurrentPage={page => this.setState({ page })} 
      currentPage={this.state.page}
    />
  }
}
```

Then change handlePage to say 

```
  onHandlePage = (page) => {
    let action = select(fetchPosts({ page: page  }), models)
    if (action.needsFetch) {
      this.props.dispatch(action.fetch)
    }
    this.props.changeCurrentPage(page)
  }
```

**Comment by shengnian** [comment]
thanks a lot, i'll try to submit PR.

**Comment by devvmh** [comment]
for what it's worth, the typical app would store the page number in the
url (with react router) or in the store under a different key. Both these
options dont require a code change

**Comment by shengnian** [comment]
you are right,  more typical app use the page number in  query string, but else some like 'Single page' (CRUD, pagination at one page) that's useful.  i didn't PR pagination features (I think this issues can solved), only a little issues.

**Comment by devvmh** [comment]
I'm closing this issue; feel free to re-open or open a new issue if you have more questions
