### ISSUE TITLE
Response without data field, how to handle?

### ISSUE THREAD

**Issue by kolyasya** [uniqueway/redux-crud-store#60]
Hello!
In my case I have no data field in server response.
This causes an error:
```
Payload is not an array! Your server response for a FETCH action
          should be in one of the following forms:

          { data: [ ... ] }

          or

          [ ... ]
        
          Here are the contents of your action:
```

What is the best way to use custom response schema? It seems like I just can override something, but I didn't understood if you have any API for it.

**Comment by devvmh** [comment]
Can you post the shape of your server response?

Thrre may be a clever way to do it, or maybe we can improve the library, but the short answer is to copy the ApiClient out of this repo into your codebase and modify as needed.

But yeah, post an example of your server response and I can let you know if there's an easier way

**Comment by kolyasya** [comment]
@devvmh thank you! Here is an example:

```
{
  "page": 1,
  "perPage": 20,
  "sort": "email",
  "order": "asc",
  "_embedded": {
    "count": 1,
    "pages": 1,
    "patients": [
      {
        "id": "2b275cc8-698e-4da7-bd51-d710461cd074",
        [[[...other fields here...]]]
        "_type": "patient",
        "_links": {
          "read": {
            "href": "/api/patients/2b275cc8-698e-4da7-bd51-d710461cd074",
            "method": "GET"
          },
          "update": {
            "href": "/api/patients/2b275cc8-698e-4da7-bd51-d710461cd074",
            "method": "PATCH"
          },
          "delete": {
            "href": "/api/patients/2b275cc8-698e-4da7-bd51-d710461cd074",
            "method": "DELETE"
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "/api/patients?page=1&perPage=1&order=asc",
      "method": "GET"
    },
    "create": {
      "href": "/api/patients",
      "method": "POST"
    }
  },
  "_type": "patient-search"
}
```

**Comment by devvmh** [comment]
Ah yes, then you're precisely the case identified in this open issue:

https://github.com/devvmh/redux-crud-store/issues/6

The quick fix is to fork ApiClient and copy into your codebase

If you come up with a nice generalized way of doing it that would be
amazing and i could help review a pull request to get this merged in for
future users.

**Comment by devvmh** [comment]
I'm closing this issue; feel free to re-open or open a new issue if you have more questions
