### ISSUE TITLE
Examples for create/update/delete?

### ISSUE THREAD

**Issue by NullVoxPopuli** [uniqueway/redux-crud-store#61]
all the component examples on the readme are for fetching data (and one for status)

it'd be nice to also have an example for something that takes an id/params.

for example, I have this (but I get an error):
```js
export default connect(
  (state, ownProps) => {
    const token = paramFromLocation(ownProps.location, 'token');
    console.log(token);

    return {
      invitation: select(invitationsAPI.update({id: token || ''})),
    };
  }
)(Invitations);
```
where update is genericly defined as:
```js
    update: ({id, ...data}, params = {}) => updateRecord(
      model, id, `${path}/${id}`, data, params, {/* auth stuff */}
    ),
```

error:
![image](https://user-images.githubusercontent.com/199018/33621487-e4e58476-d9b8-11e7-9341-112bb6c9aabb.png)
which is kinda weird... PATCH requests are supposed to return the whole resource in their response -- so I'm not sure what's up (the request isn't made though (it hasn't gotten that far))

**Comment by devvmh** [comment]
That's a great point. I do have a demo app I've been using for testing here 

https://github.com/devvmh/demo-redux-crud-store/blob/master/src/Posts/edit.js

this also has other examples (browse the Posts/ folder in the repo) but overall it's suuuuper stripped down. A real app would probably be cleverer about how it used the create/update/delete actions.

Would you be willing to make a pull request?

**Comment by NullVoxPopuli** [comment]
@devvmh  I did eventually find those. :-)
Follow up question -- in order to update, do I need to have the record locally?
Or can I do an update without having the record?

![image](https://user-images.githubusercontent.com/199018/33622545-1dfa9582-d9bc-11e7-90b5-d7665336f15d.png)

My code:
```js
  componentDidMount() {
    const { status, dispatch, location } = this.props;

    if (status.id === null) {
      const token = paramFromLocation(location, 'token');

      dispatch(invitationsAPI.update({id: token}));
    }
  }
```
I'm just trying to do an 'accept invite' kind of workflow where the frontend is hit first so feedback can be presented to the user as fast as possible. (opposed to accepting the invite on the server (which would involve non-api server-routing as well)) :-)

**Comment by devvmh** [comment]
I guess that debugger screenshot is of the code in reducers.js right? That might be a fixable bug, you can open another issue for it. Chances are I did assume the record was present for an update and the reducer could be fixed

**Comment by NullVoxPopuli** [comment]
done: https://github.com/devvmh/redux-crud-store/issues/62

and yes, the debugger screen shot is from the reducers file :-)
