### ISSUE TITLE
TypeError: payload.forEach is not a function

### ISSUE THREAD

**Issue by recurser** [uniqueway/redux-crud-store#64]
I'm getting an error `TypeError: payload.forEach is not a function` parsing the response from a JSON API endpoint.

Specifically, [this response](https://gist.github.com/recurser/23fc68358024ff8bc84596a006821ad7) triggers the error. You can run [this gist](https://gist.github.com/recurser/6c0779420c004c659afb1d397abeb9c5) to see the error in action.

Removing the top-level `{"data": ...}` wrapping (ie. returning an array [like this](https://gist.github.com/recurser/3b9a6c97ba74349c92a9dd46aead3eff) instead of an object) works fine, but I don't have the option to change the data returned by the API endpoint unfortunately. [Here's a gist](https://gist.github.com/recurser/4b3aacf90e39fd29d26a5b9a0433148f) showing it working with the altered data structure.

As far as I can tell I'm complying with the `{ data: [ ... ] }` structure required by `redux-crud-store`. Any idea what I'm doing wrong here, or how I might be able get it working?

**Comment by recurser** [comment]
According to `git-bisect`, the culprit is https://github.com/devvmh/redux-crud-store/commit/deb337033158986195939653e4080b4b252bec68

**Comment by devvmh** [comment]
Thanks for the detailed report. I've just looked briefly and can't see the problem but I will take another look tonight to see what I can figure out. FWIW your data format seems fine to me, so it should work.

git-bisect is presumably tagging that commit because it's when I updated the lib/ folder. Based on the commits noted at https://github.com/devvmh/redux-crud-store/releases, I'm guessing it happened when I removed Immutable.JS from the library.

There are ideally no changes between 5.3.0 and 5.4.0 other than the ImmutableJS removal so you should be fine to use 5.3.0 for now until I can find/fix the problem

**Comment by NullVoxPopuli** [comment]
I'm getting this error, too.
we have jsonapi.org formatted payloads

**Comment by NullVoxPopuli** [comment]
I get payload.map is not a function on 5.3 and 5.4 (with the full jsonapi document)

if I just return response.data, (from a custom api client), redux-crud-store doesn't error.

I'd like to be able to properly make use of the included relationships, though.

**Comment by recurser** [comment]
> There are ideally no changes between 5.3.0 and 5.4.0 other than the ImmutableJS removal so you should be fine to use 5.3.0 for now until I can find/fix the problem

@devvmh yes `5.3.0` works great 👍 Interestingly deb337033158986195939653e4080b4b252bec68 (`Remove immutable js #49`) also seems to work.

**Comment by NullVoxPopuli** [comment]
@recurser I found this: https://github.com/ShadowManu/jsonapi-deserializer
and am using it in my alternate api client:

unfortunately, a lot of the default api client is built in the constructor, so I can't properly extend it.
But, in spite of that, @devvmh this library (redux-crud-store) is a life saver. Been so tired of the same boilerplate api/data handling being re-implemented on every project, thanks a ton!


```js
import { deserialize } from 'jsonapi-deserializer';

// https://github.com/devvmh/redux-crud-store/blob/master/src/ApiClient.js
export default class ApiClient {
  constructor(passedConfig) {
    const baseConfig = {
      bodyEncoder: JSON.stringify,
      credentials: 'same-origin',
      format: 'json',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      methods: ['get', 'post', 'put', 'patch', 'delete']
    }

    if (!passedConfig.basePath) {
      // e.g. 'https://example.com/api/v3'
      throw new Error('You must pass a base path to the ApiClient')
    }

    const methods = passedConfig.methods || baseConfig.methods
    methods.forEach(method => {
      this[method] = (path, { params, data, fetchConfig } = {}) => {
        const config = {
          ...baseConfig,
          ...passedConfig,
          ...fetchConfig,
          headers: {
            ...baseConfig.headers,
            ...(passedConfig ? passedConfig.headers : {}),
            ...(fetchConfig ? fetchConfig.headers : {})
          }
        }
        const {
          methods: _methods, basePath, headers, format, bodyEncoder,
          ...otherConfig
        } = config
        const requestPath = basePath + path + this.queryString(params)
        const body = data ? bodyEncoder(data) : undefined

        return fetch(requestPath, {
          ...otherConfig,
          method,
          headers,
          body
        }).then(response => ({ response, format }))
          .then(this.handleErrors)
          .then(this.handleResponse(format))
      }
    })
  }

  // thanks http://stackoverflow.com/a/12040639/5332286
  queryString(params) {
    const s = Object.keys(params).map(key => (
      [key, params[key]].map(encodeURIComponent).join('=')
    )).join('&')
    return s ? `?${s}` : ''
  }


   handleResponse(format) {
    return async response => {
      const jsonApiDocument = await response[format]();

      const deserialized = deserialize(jsonApiDocument);
      console.log(deserialized)
      return deserialized;
    }
  }

  handleErrors({ response, format }) {
    if (!response.ok) {
      return response[format]()
        // if response parsing failed send back the entire response object
        .catch(() => { throw response })
        // else send back the parsed error
        .then(parsedErr => { throw parsedErr })
    }
    return response
  }

}
```

**Comment by devvmh** [comment]
OK, I finally reproduced this locally using a netcat mocked web server (my browser complains about github not sending headers or something about CORS):

```
while true; do
  {
    echo -e 'HTTP/1.1 200 OK\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Headers: content-type\r\nAllow: HEAD,GET,PUT,DELETE,OPTIONS\r\n'
  } | nc -l 8080
  {
    echo -e 'HTTP/1.1 200 OK\r\nAccess-Control-Allow-Origin: *\r\n\r\n'; cat test.json;
  } | nc -l 8080
done
```

**Comment by devvmh** [comment]
in the saga, when I `put` the action, the payload is `{ data: [ ... ] }` like it should be

**Comment by devvmh** [comment]
ah, got it.

modelReducerImpl calls collectionReducerImpl and then byIdReducerImpl. collectionReducerImpl has a bug where it mutates the action.payload in the case of a data envelope (deleting the entire payload)

https://github.com/devvmh/redux-crud-store/blob/master/src/reducers.js#L145

so then byIdReducerImpl fails.

PR inbound

**Comment by recurser** [comment]
> PR inbound

Great, thanks @devvmh 👍 

> @devvmh this library (redux-crud-store) is a life saver. Been so tired of the same boilerplate api/data handling being re-implemented on every project, thanks a ton!

Second that @NullVoxPopuli ! 🍻
